spring.application.name=delhi
server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.devtools.restart.enabled=false
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}